// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      'autoUpdate': boolean;
      'source': string;
      'customSource': string;
      'hideToolbarEntrance': boolean;
      'guideStatus': number;
      'firstInstalledVersion': string;
    };
  }
}
